"""AWS Network Firewall RawEvent → SecurityEvent normalization.

AWS NFW's stateful engine IS Suricata; its alert log records are EVE JSON wrapped
in an AWS CloudWatch Logs envelope:

  {"firewall_name": "...", "availability_zone": "...", "event_timestamp": "...",
   "event": { <Suricata EVE JSON> }}

So normalize() strips the AWS envelope and delegates to the same mapping logic
as the Suricata EVE normalizer — the strongest possible evidence the contract
generalizes across clouds (per docs/contract-stress-2026-06.md §Source 1).

Reference: AWS Network Firewall Developer Guide — Stateful engine alert logging
  https://docs.aws.amazon.com/network-firewall/latest/developerguide/logging-cw-logs.html

Field mapping (docs/contract-stress-2026-06.md §Source 1 normalize table):
  event.src_ip / event.dest_ip     → source_ip / destination_ip
  event.src_port / event.dest_port → source_port / destination_port
  event.proto                      → protocol
  event.alert.action               → action (blocked→BLOCK, alert→ALERT, ADR-0012)
  event.alert.signature_id         → rule_id
  event.alert.signature            → rule_name
  event.alert.severity             → severity (1=high...4=info, ADR-0069 D4a, same as Suricata)
  event.alert.category             → category (via SURICATA_CATEGORY_MAP)
  event.alert.metadata.mitre_*     → attack_technique / attack_tactic (ADR-0014)
  event.flow_id                    → source_event_id
  event.http.url / event.http.hostname → http_url / http_host (ADR-0048 Group D)
  event.http.http_method           → http_method (ADR-0048 Group D)
  event.tls.sni / event.tls.version → tls_sni / tls_version (ADR-0048 Group C)
  event.tls.ja4 / event.tls.ja4s  → tls_ja4 / tls_ja4s (ADR-0048 Group C)
  event.flow.bytes_toserver/toclient → bytes_out / bytes_in (ADR-0048 Group A)
  event.flow.pkts_toserver/toclient  → packets_out / packets_in (ADR-0048 Group A)
  event.flow.start/end             → flow_duration_ms (ADR-0048 Group A)
  event.dns.rrname / event.dns.rcode → dns_query / dns_rcode (ADR-0048 Group B)

OCSF alignment (ADR-0020):
  ocsf_class=2004 (Detection Finding), ocsf_category=2 (Findings)
  Source: https://schema.ocsf.io/classes/detection_finding
  "detections or alerts generated by security products such as antivirus, EDR,
  network security monitoring" — exactly what NFW Suricata IDS/IPS is.

source_type is ALWAYS the constant "aws_network_firewall" — this plugin owns that mapping.
source_id is the caller-supplied instance name; this function never branches on it (Flag B).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from firewatch_sdk import RawEvent, SecurityEvent

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SOURCE_TYPE: str = "aws_network_firewall"

# OCSF Detection Finding (ADR-0020).
# class_uid=2004: "detections or alerts generated by security products such as
# antivirus, EDR, network security monitoring" — exactly what NFW Suricata IDS/IPS is.
# category_uid=2: Findings.
# Source: https://schema.ocsf.io/classes/detection_finding
OCSF_CLASS: int = 2004
OCSF_CATEGORY: int = 2

# ---------------------------------------------------------------------------
# Category map (reused from Suricata EVE — same engine, same categories)
# ---------------------------------------------------------------------------

# Ported from firewatch_suricata/normalize.py SURICATA_CATEGORY_MAP.
# AWS NFW stateful engine is Suricata; its alert.category values are identical.
SURICATA_CATEGORY_MAP: dict[str, str] = {
    "Web Application Attack":                  "Web Attack (IDS)",
    "Attempted Information Leak":              "Recon (IDS)",
    "Information Leak":                        "Recon (IDS)",
    "Misc Attack":                             "Misc Attack (IDS)",
    "A Network Trojan was detected":           "Trojan (IDS)",
    "Trojan Activity":                         "Trojan (IDS)",
    "Detection of a Network Scan":             "Port Scan (IDS)",
    "A suspicious string was detected":        "Suspicious (IDS)",
    "Generic Protocol Command Decode":         "Protocol Anomaly (IDS)",
    "Potentially Bad Traffic":                 "Suspicious (IDS)",
    "Attempted Administrator Privilege Gain":  "Privilege Escalation (IDS)",
    "Successful Administrator Privilege Gain": "Privilege Escalation (IDS)",
    "Attempted User Privilege Gain":           "Privilege Escalation (IDS)",
    "Web Application User":                    "Web Attack (IDS)",
    "Misc activity":                           "IDS Alert",
}

# ADR-0069 D4(a) — recalibrated against Sigma's behavioral `level` vocabulary
# (SigmaHQ/sigma-specification, `specification/sigma-rules-specification.md`) and
# Suricata's shipped `classification.config`
# (https://raw.githubusercontent.com/OISF/suricata/master/etc/classification.config,
# quoted in ADR-0068/ADR-0069). AWS NFW's stateful engine IS Suricata, so this map
# MUST stay identical to firewatch_suricata's — a shared test asserts that.
# Suricata integer severity (1=highest priority) → FireWatch severity string.
_SEVERITY_MAP: dict[int, str] = {
    # "should trigger an internal alert and requires a prompt review" (Sigma high) —
    # not `critical`: Sigma reserves that for "probability borders certainty," and a
    # single ET signature match is well-documented as FP-prone.
    1: "high",
    # "Relevant event that should be reviewed manually on a more frequent basis"
    # (Sigma medium) — this class (attempted-recon/misc-attack) is ambient at volume
    # on every internet-exposed sensor (ADR-0068 fact 1); the D1 distribution
    # corollary makes anything higher than `medium` definitionally wrong here.
    2: "medium",
    # "Notable event but rarely an incident... relevant in high numbers or
    # combination with others" (Sigma low) — ET INFO (misc-activity) verbatim.
    3: "low",
    # "expected that a huge amount of events will match" (Sigma informational) —
    # the below-low ordinal floor; unused by the shipped classification.config
    # (reachable via custom classifications only).
    4: "info",
}

# ADR-0069 D3 rule 4 (fail quiet): missing/unparseable/unrecognized severity maps
# to "low" (telemetry-grade) — never fabricated upward to a level that would
# qualify the actor for Tier-2 triage on its own (ADR-0067 D1(b)).
_FAIL_QUIET_SEVERITY = "low"


def _map_severity(raw_severity: Any) -> str:
    """Translate Suricata's integer priority into a FireWatch severity level.

    ADR-0069 D4(a): see ``_SEVERITY_MAP`` for the per-value Sigma justification.
    Missing (``None``) or unparseable (non-integer) values fail quiet to "low"
    (D3 rule 4) rather than defaulting to a mid-scale value that could still
    qualify for triage.
    """
    if raw_severity is None:
        return _FAIL_QUIET_SEVERITY
    try:
        sev_int = int(raw_severity)
    except (ValueError, TypeError):
        return _FAIL_QUIET_SEVERITY
    return _SEVERITY_MAP.get(sev_int, _FAIL_QUIET_SEVERITY)

# Action map: AWS NFW Suricata alert.action values → FireWatch action (ADR-0012).
# "blocked" = IPS mode (packet dropped); "alert" = IDS mode (detected, not dropped).
_ACTION_MAP: dict[str, str] = {
    "blocked": "BLOCK",
    "alert":   "ALERT",
    "pass":    "ALLOW",
}
_DEFAULT_ACTION = "ALERT"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _flow_duration_ms(flow: dict[str, Any]) -> int | None:
    """Compute flow duration in ms from EVE flow.start / flow.end ISO strings.

    Returns None if either key is absent or unparseable — honest over approximate.
    ADR-0048 Group A: stored as ms (OCSF has no first-class duration scalar on
    Network Activity; ECS anchor is event.duration in ns).
    """
    start_str: str | None = flow.get("start")
    end_str: str | None = flow.get("end")
    if not start_str or not end_str:
        return None
    try:
        start_dt = datetime.fromisoformat(start_str.replace("Z", "+00:00"))
        end_dt = datetime.fromisoformat(end_str.replace("Z", "+00:00"))
        if start_dt.tzinfo is None:
            start_dt = start_dt.replace(tzinfo=timezone.utc)
        if end_dt.tzinfo is None:
            end_dt = end_dt.replace(tzinfo=timezone.utc)
        delta_ms = int((end_dt - start_dt).total_seconds() * 1000)
        return delta_ms if delta_ms >= 0 else None
    except (ValueError, AttributeError, OverflowError):
        return None


# ---------------------------------------------------------------------------
# Public normalize function
# ---------------------------------------------------------------------------


def normalize(raw: RawEvent, source_id: str) -> SecurityEvent:
    """Map an AWS NFW RawEvent (EVE-in-AWS-envelope) to a SecurityEvent.

    Implements PLUGIN_CONTRACT.md normalize() for the AWS Network Firewall source.
    source_type is always "aws_network_firewall" (constant — Flag B).
    source_id is the caller's instance name; never branched on.

    The AWS CloudWatch Logs envelope {"firewall_name":…, "event":{<EVE>}} is stripped;
    normalization then follows the Suricata EVE mapping (same stateful engine).

    Never fabricates fields not present in the log record.
    """
    d = raw.data

    # Strip AWS envelope — inner EVE record lives under "event" key.
    eve: dict[str, Any] = d.get("event") or d

    alert: dict[str, Any] = eve.get("alert") or {}
    metadata_tags: dict[str, Any] = alert.get("metadata") or {}

    # ── Timestamp ─────────────────────────────────────────────────────────────
    ts_str = eve.get("timestamp", "")
    try:
        timestamp = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=timezone.utc)
    except (ValueError, AttributeError):
        timestamp = raw.received_at

    # ── Action (ADR-0012) ─────────────────────────────────────────────────────
    raw_action = str(alert.get("action") or "").strip().lower()
    action: str = _ACTION_MAP.get(raw_action, _DEFAULT_ACTION)

    # ── Category ─────────────────────────────────────────────────────────────
    category: str = SURICATA_CATEGORY_MAP.get(
        str(alert.get("category") or ""), "IDS Alert"
    )

    # ── Severity (ADR-0069 D4a) ───────────────────────────────────────────────
    # Guard against non-integer severity values (same as Suricata NB-4 fix).
    severity: str = _map_severity(alert.get("severity"))

    # ── Rule ─────────────────────────────────────────────────────────────────
    sig_id = alert.get("signature_id")
    rule_id: str | None = str(sig_id) if sig_id is not None else None
    rule_name: str | None = alert.get("signature") or None

    # ── Source event ID (flow-level dedup) ────────────────────────────────────
    flow_id = eve.get("flow_id")
    source_event_id: str | None = str(flow_id) if flow_id is not None else None

    # ── MITRE ATT&CK from ET Open metadata (ADR-0014) ─────────────────────────
    technique_ids: list[str] = metadata_tags.get("mitre_technique_id") or []
    attack_technique: str | None = technique_ids[0] if technique_ids else None

    tactic_ids: list[str] = metadata_tags.get("mitre_tactic_id") or []
    attack_tactic: str | None = tactic_ids[0] if tactic_ids else None

    # ── ADR-0048 Group A: flow volume & duration ──────────────────────────────
    flow_obj: dict[str, Any] = eve.get("flow") or {}
    bytes_in: int | None = flow_obj.get("bytes_toclient")
    bytes_out: int | None = flow_obj.get("bytes_toserver")
    packets_in: int | None = flow_obj.get("pkts_toclient")
    packets_out: int | None = flow_obj.get("pkts_toserver")
    flow_duration_ms: int | None = _flow_duration_ms(flow_obj) if flow_obj else None

    # ── ADR-0048 Group B: DNS ─────────────────────────────────────────────────
    dns_obj: dict[str, Any] = eve.get("dns") or {}
    dns_query: str | None = dns_obj.get("rrname") or None
    dns_rcode: str | None = dns_obj.get("rcode") or None

    # ── ADR-0048 Group C: TLS / JA4 ──────────────────────────────────────────
    # AWS NFW may emit tls.ja4/ja4s when Suricata 7.x JA4 support is enabled.
    # Do NOT copy tls.ja3 into tls_ja4 — they are different fingerprint algorithms.
    tls_obj: dict[str, Any] = eve.get("tls") or {}
    tls_sni: str | None = tls_obj.get("sni") or None
    tls_version: str | None = tls_obj.get("version") or None
    tls_ja4: str | None = tls_obj.get("ja4") or None
    tls_ja4s: str | None = tls_obj.get("ja4s") or None

    # ── ADR-0048 Group D: HTTP ────────────────────────────────────────────────
    http_obj: dict[str, Any] = eve.get("http") or {}
    http_url: str | None = http_obj.get("url") or None
    http_host: str | None = http_obj.get("hostname") or None
    http_method: str | None = http_obj.get("http_method") or None
    http_user_agent: str | None = http_obj.get("http_user_agent") or None

    # ── Payload snippet ───────────────────────────────────────────────────────
    payload_snippet: str | None = None
    if http_url:
        raw_snippet = (http_host + http_url) if http_host else http_url
        payload_snippet = raw_snippet[:500]

    return SecurityEvent(
        source_type=SOURCE_TYPE,   # constant — never branches on source_id (Flag B)
        source_id=source_id,       # caller's instance name, passed through as-is
        source_event_id=source_event_id,
        timestamp=timestamp,
        source_ip=eve.get("src_ip") or "",
        source_port=eve.get("src_port"),
        destination_ip=eve.get("dest_ip"),
        destination_port=eve.get("dest_port"),
        protocol=eve.get("proto"),
        action=action,  # type: ignore[arg-type]
        category=category,
        severity=severity,  # type: ignore[arg-type]
        ocsf_class=OCSF_CLASS,
        ocsf_category=OCSF_CATEGORY,
        rule_id=rule_id,
        rule_name=rule_name,
        payload_snippet=payload_snippet,
        attack_technique=attack_technique,
        attack_tactic=attack_tactic,
        # ADR-0048 network-depth fields
        bytes_in=bytes_in,
        bytes_out=bytes_out,
        packets_in=packets_in,
        packets_out=packets_out,
        flow_duration_ms=flow_duration_ms,
        dns_query=dns_query,
        dns_rcode=dns_rcode,
        tls_ja4=tls_ja4,
        tls_ja4s=tls_ja4s,
        tls_sni=tls_sni,
        tls_version=tls_version,
        http_method=http_method,
        http_host=http_host,
        http_url=http_url,
        http_user_agent=http_user_agent,
        raw_log=d,
    )
