"""Scaffold generator for FireWatch source plugins.

Called by ``firewatch new-source <name>``.  Generates a ready-to-edit plugin
package under ``<output_dir>/packages/sources/<name>/`` with:

  - pyproject.toml       — ``firewatch-sdk``-only deps + entry-point wiring
  - src/firewatch_<name>/__init__.py
  - src/firewatch_<name>/plugin.py  — SourcePlugin + Pull/Push flavor stubs
  - src/firewatch_<name>/config.py  — Pydantic config with SecretStr + env>file>default
  - src/firewatch_<name>/normalize.py — SecurityEvent mapping stub with TODOs + NB-1 note
  - src/firewatch_<name>/collector.py (pull) or listener.py (push)
  - tests/__init__.py
  - tests/test_plugin.py    — entry-point isolation test + SourcePlugin conformance
  - tests/test_normalize.py — golden-test stub the author fills in

The generated package imports ``firewatch-sdk`` ONLY — never ``firewatch-core``
or ``legacy/`` (PLUGIN_CONTRACT.md hard rule).

``type_key`` constraint: must match ``^[a-z][a-z0-9_]*$`` — must start with a lowercase letter
(leading underscore is reserved for core; see PLUGIN_CONTRACT.md and ADR-0025).
"""
from __future__ import annotations

import re
from pathlib import Path
from string import Template


# ---------------------------------------------------------------------------
# Name validation
# ---------------------------------------------------------------------------

_TYPE_KEY_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def validate_name(name: str) -> None:
    """Raise ``ValueError`` if *name* is not a valid source type_key.

    PLUGIN_CONTRACT.md: ``type_key`` must match ``^[a-z][a-z0-9_]*$``
    (must start with a lowercase letter; leading underscore is reserved for core).
    """
    if not name:
        raise ValueError("Source name must not be empty.")
    if not _TYPE_KEY_RE.match(name):
        raise ValueError(
            f"Source name {name!r} is invalid. "
            "It must match ^[a-z][a-z0-9_]*$ (must start with a lowercase letter; "
            "digits and underscores may follow). "
            "Example: 'azure_waf', 'syslog2', 'mywidget'."
        )


# ---------------------------------------------------------------------------
# Template helpers
# ---------------------------------------------------------------------------

def _camel(name: str) -> str:
    """Convert snake_case name to CamelCase for use as a class name.

    Examples:
      'mywidget'   -> 'Mywidget'
      'my_widget'  -> 'MyWidget'
      'azure_waf2' -> 'AzureWaf2'
    """
    return "".join(part.capitalize() for part in name.split("_"))


def _env_prefix(name: str) -> str:
    """Return the env-var prefix for the source: FIREWATCH_<NAME>_."""
    return f"FIREWATCH_{name.upper()}_"


# ---------------------------------------------------------------------------
# File templates
# ---------------------------------------------------------------------------

_PYPROJECT_TMPL = Template("""\
[project]
name = "firewatch-${name}"
version = "0.1.0"
description = "FireWatch ${title} source plugin — generated by firewatch new-source."
requires-python = ">=3.12"
dependencies = [
    "firewatch-sdk",
    "pydantic>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/firewatch_${name}"]

[project.entry-points."firewatch.sources"]
${name} = "firewatch_${name}.plugin:${class_name}Source"
""")

_INIT_TMPL = Template("""\
"""
)

_PLUGIN_PULL_TMPL = Template("""\
\"\"\"${class_name}Source — FireWatch PullSource plugin stub.

Registered as ``${name}`` under the ``firewatch.sources`` entry-point group.
Adding this package to the workspace requires zero edits to firewatch-core
(PLUGIN_CONTRACT.md modularity guarantee).

This module implements:
  - ``SourcePlugin`` (metadata, config_schema, validate_config, normalize, health_check)
  - ``PullSource`` (collect)

It depends on ``firewatch-sdk`` ONLY. Never imports firewatch-core or legacy/.

TODO: Replace every ``# TODO`` comment in this file with real implementation.
\"\"\"
from __future__ import annotations

from collections.abc import AsyncIterator

from pydantic import BaseModel

from firewatch_sdk import PluginContext, RawEvent, SecurityEvent, SourceMetadata

from firewatch_${name} import normalize as _normalize
from firewatch_${name}.config import ${class_name}Config

# Plugin version — SemVer string (PLUGIN_CONTRACT.md SourceMetadata.version).
_VERSION = "0.1.0"

# The canonical type key for this source. Must match the entry-point name and
# the regex ^[a-z][a-z0-9_]*$$ (PLUGIN_CONTRACT.md / ADR-0025: must start with
# a lowercase letter; leading underscore reserved for core).
_TYPE_KEY = "${name}"


class ${class_name}Source:
    \"\"\"${title} source plugin.

    Implements ``SourcePlugin`` + ``PullSource`` from firewatch-sdk.

    TODO: Describe the collection mechanism (SSH, HTTP poll, file tail, …).

    Normalization (ADR-0012, ADR-0014, ADR-0016):
      - ``source_type`` is the constant ``"${name}"`` — never branches on ``source_id``.
      - TODO: document action mapping (ALERT vs BLOCK) per ADR-0012.
    \"\"\"

    # ── SourcePlugin methods ─────────────────────────────────────────────────

    def metadata(self) -> SourceMetadata:
        return SourceMetadata(
            type_key=_TYPE_KEY,
            display_name="${title}",
            version=_VERSION,
            flavor="pull",
        )

    def config_schema(self) -> type[BaseModel]:
        \"\"\"Return the Pydantic model that drives the rjsf UI source card.

        Config resolution respects env > file > default (ADR-0006); use
        ``build_config()`` at runtime to construct the instance.
        \"\"\"
        return ${class_name}Config

    def validate_config(self, cfg: dict) -> None:  # type: ignore[type-arg]
        \"\"\"Validate a raw config dict. Raises ``pydantic.ValidationError`` if invalid.\"\"\"
        ${class_name}Config.model_validate(cfg)

    def normalize(self, raw: RawEvent, source_id: str) -> SecurityEvent:
        \"\"\"Map a raw event to a SecurityEvent.

        ``source_type`` is always ``"${name}"`` (this plugin's constant).
        ``source_id`` is the caller's instance name, passed through as-is.
        This method MUST NOT branch on ``source_id`` (Flag B, PLUGIN_CONTRACT.md).
        \"\"\"
        return _normalize.normalize(raw, source_id)

    async def health_check(self, cfg: BaseModel) -> bool:
        \"\"\"Return True if the configured source is reachable/readable.

        TODO: Implement a lightweight connectivity check.
        Returns False (never raises) on any failure.
        \"\"\"
        try:
            ${class_name}Config.model_validate(cfg.model_dump())
        except Exception:
            return False
        # TODO: perform a real check (e.g. try to open the file / connect)
        return True

    # ── PullSource method ────────────────────────────────────────────────────

    async def collect(
        self, cfg: BaseModel, since: str | None, ctx: PluginContext
    ) -> AsyncIterator[RawEvent]:
        \"\"\"Yield ``RawEvent``s newer than ``since`` (an ISO-8601 watermark, or None).

        Must be cancellable; must not raise out of its loop (PLUGIN_CONTRACT.md).

        ``ctx.kv`` is the ONLY persistence handle available to this plugin (ADR-0027 /
        ADR-0025). ``ctx.source_id`` is for labelling/logging only — never branch on it.

        TODO: Replace this stub with the real collection loop.
        \"\"\"
        # TODO: implement collection — iterate your source, filter by `since`,
        # yield RawEvent(source_type=_TYPE_KEY, received_at=..., data=<raw dict>)
        return
        yield  # pragma: no cover  (makes this an async generator)
""")

_PLUGIN_PUSH_TMPL = Template("""\
\"\"\"${class_name}Source — FireWatch PushSource plugin stub.

Registered as ``${name}`` under the ``firewatch.sources`` entry-point group.
Adding this package to the workspace requires zero edits to firewatch-core
(PLUGIN_CONTRACT.md modularity guarantee).

This module implements:
  - ``SourcePlugin`` (metadata, config_schema, validate_config, normalize, health_check)
  - ``PushSource`` (start, stop)

It depends on ``firewatch-sdk`` ONLY. Never imports firewatch-core or legacy/.

TODO: Replace every ``# TODO`` comment in this file with real implementation.
\"\"\"
from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable

from pydantic import BaseModel

from firewatch_sdk import PluginContext, RawEvent, SecurityEvent, SourceMetadata

from firewatch_${name} import normalize as _normalize
from firewatch_${name}.config import ${class_name}Config

# Plugin version — SemVer string (PLUGIN_CONTRACT.md SourceMetadata.version).
_VERSION = "0.1.0"

# The canonical type key for this source. Must match the entry-point name and
# the regex ^[a-z][a-z0-9_]*$$ (PLUGIN_CONTRACT.md / ADR-0025: must start with
# a lowercase letter; leading underscore reserved for core).
_TYPE_KEY = "${name}"


class ${class_name}Source:
    \"\"\"${title} source plugin.

    Implements ``SourcePlugin`` + ``PushSource`` from firewatch-sdk.

    TODO: Describe the listener (UDP/TCP syslog, webhook, …).

    Normalization (ADR-0012, ADR-0014, ADR-0016):
      - ``source_type`` is the constant ``"${name}"`` — never branches on ``source_id``.
      - TODO: document action mapping (ALERT vs BLOCK) per ADR-0012.
    \"\"\"

    def __init__(self) -> None:
        self._stop_event: asyncio.Event = asyncio.Event()

    # ── SourcePlugin methods ─────────────────────────────────────────────────

    def metadata(self) -> SourceMetadata:
        return SourceMetadata(
            type_key=_TYPE_KEY,
            display_name="${title}",
            version=_VERSION,
            flavor="push",
        )

    def config_schema(self) -> type[BaseModel]:
        \"\"\"Return the Pydantic model that drives the rjsf UI source card.

        Config resolution respects env > file > default (ADR-0006); use
        ``build_config()`` at runtime to construct the instance.
        \"\"\"
        return ${class_name}Config

    def validate_config(self, cfg: dict) -> None:  # type: ignore[type-arg]
        \"\"\"Validate a raw config dict. Raises ``pydantic.ValidationError`` if invalid.\"\"\"
        ${class_name}Config.model_validate(cfg)

    def normalize(self, raw: RawEvent, source_id: str) -> SecurityEvent:
        \"\"\"Map a raw event to a SecurityEvent.

        ``source_type`` is always ``"${name}"`` (this plugin's constant).
        ``source_id`` is the caller's instance name, passed through as-is.
        This method MUST NOT branch on ``source_id`` (Flag B, PLUGIN_CONTRACT.md).
        \"\"\"
        return _normalize.normalize(raw, source_id)

    async def health_check(self, cfg: BaseModel) -> bool:
        \"\"\"Return True if listener configuration is valid and ports are bindable.

        TODO: Implement a lightweight port-probe check.
        Returns False (never raises) on any failure.
        \"\"\"
        try:
            ${class_name}Config.model_validate(cfg.model_dump())
        except Exception:
            return False
        # TODO: probe the bind address / port
        return True

    # ── PushSource methods ───────────────────────────────────────────────────

    async def start(
        self,
        cfg: BaseModel,
        emit: Callable[[list[RawEvent]], Awaitable[None]],
        ctx: PluginContext,
    ) -> None:
        \"\"\"Bind the listener and run until stop() is called.

        Must be cancellable; must not raise out of its loop (PLUGIN_CONTRACT.md).

        ``ctx.kv`` is the ONLY persistence handle available to this plugin (ADR-0027 /
        ADR-0025). ``ctx.source_id`` is for labelling/logging only — never branch on it.

        TODO: Replace this stub with the real listener loop.
        \"\"\"
        self._stop_event = asyncio.Event()
        # TODO: spawn listener tasks, feed received bytes to emit([RawEvent(...)])
        await self._stop_event.wait()

    async def stop(self) -> None:
        \"\"\"Signal the listener to exit and release sockets.

        Safe to call before start() or multiple times.
        \"\"\"
        self._stop_event.set()
""")

_CONFIG_TMPL = Template("""\
\"\"\"${class_name} plugin configuration.

Resolution order (ADR-0006): env vars > firewatch_config.json > hardcoded defaults.

``${class_name}Config`` is the Pydantic model returned by ``config_schema()``. It drives the
rjsf UI source card.

``build_config`` constructs a resolved instance following the precedence chain. The UI
calls it with ``config_file`` pointing at the persisted ``firewatch_config.json``; tests
pass a ``tmp_path`` file or ``None`` to isolate env-var reads.

TODO: Add or remove fields for your source. Every secret field must use ``SecretStr``
(PLUGIN_CONTRACT.md hard rule). Add corresponding entries to ``_ENV_MAP``.
\"\"\"
import json
import logging
import os
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, SecretStr

logger = logging.getLogger("firewatch.${name}.config")


# ---------------------------------------------------------------------------
# Pydantic model — drives the rjsf UI card (PLUGIN_CONTRACT.md config_schema)
# ---------------------------------------------------------------------------


class ${class_name}Config(BaseModel):
    \"\"\"${title} collector configuration.

    TODO: Replace these example fields with the real ones for your source.

    Secrets use ``SecretStr`` — never plain ``str`` (PLUGIN_CONTRACT.md hard rule).
    \"\"\"

    model_config = ConfigDict(extra="ignore")

    # Example plain field — replace with a real one.
    host: str = Field(
        default="",
        title="${title} host",
        description="Hostname or IP of the ${title} source. TODO: fill in your fields.",
    )

    # Example secret field — keep SecretStr for any credential/key/token.
    # PLUGIN_CONTRACT.md: secrets MUST use SecretStr, never plain str.
    api_key: SecretStr | None = Field(
        default=None,
        title="API key / token",
        description=(
            "Secret API key or token for ${title}. Leave blank if not required. "
            "TODO: rename or remove this field as appropriate."
        ),
    )


# ---------------------------------------------------------------------------
# build_config — env > file > default resolution (ADR-0006)
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_FILE = Path("firewatch_config.json")

# Mapping: config-field-name → env var name (ADR-0006 env > file > default).
# TODO: Add an entry for every field in ${class_name}Config above.
_ENV_MAP: dict[str, str] = {
    "host":     "${env_prefix}HOST",
    "api_key":  "${env_prefix}API_KEY",
}

# Fields that need integer coercion from env (add int fields here)
_INT_FIELDS: frozenset[str] = frozenset()


def build_config(
    config_file: Path | str | None = _DEFAULT_CONFIG_FILE,
) -> ${class_name}Config:
    \"\"\"Construct a ``${class_name}Config`` with env > file > default precedence (ADR-0006).

    1. Start from Pydantic defaults.
    2. Apply any values found in the ``"${name}"`` section of *config_file*.
    3. Apply env vars — these always win; they can't be overridden.

    ``config_file=None`` skips the file layer (useful in tests).
    \"\"\"
    merged: dict[str, Any] = {}

    # Layer 2: config file (lower priority than env)
    if config_file is not None:
        file_path = Path(config_file)
        if file_path.exists():
            try:
                raw = json.loads(file_path.read_text(encoding="utf-8"))
                section: dict[str, Any] = raw.get("${name}") or {}
                for key in _ENV_MAP:
                    if key in section:
                        merged[key] = section[key]
            except Exception as exc:
                logger.warning("${class_name}Config: cannot read %s: %s", file_path, exc)

    # Layer 3: env vars (highest priority — override file values)
    for field, env_var in _ENV_MAP.items():
        raw_val = os.environ.get(env_var)
        if raw_val is not None:
            if field in _INT_FIELDS:
                try:
                    merged[field] = int(raw_val)
                except ValueError:
                    logger.warning("Invalid %s value %r; ignoring", env_var, raw_val)
            elif field == "api_key" and raw_val == "":
                merged[field] = None
            else:
                merged[field] = raw_val

    return ${class_name}Config.model_validate(merged)
""")

_NORMALIZE_TMPL = Template("""\
\"\"\"${class_name} → SecurityEvent normalization stub.

TODO: Map raw vendor events to ``SecurityEvent`` fields.

Key responsibilities (PLUGIN_CONTRACT.md ``normalize()`` section):
  - Set ``source_type`` to the constant ``"${name}"`` (never from the raw event).
  - Pass ``source_id`` through unchanged — do NOT branch on it (Flag B, ADR-0016).
  - Set ``action``: detections → ``ALERT``, blocks → ``BLOCK`` (ADR-0012).
  - Set ``severity``, ``category``, ``rule_id``, ``rule_name``, ``payload_snippet``.
  - Set ``attack_technique`` / ``attack_tactic`` / ``kill_chain_phase`` / ``capec_id``
    where derivable from source metadata (ADR-0014).
  - Unmapped vendor fields stay in ``RawEvent.data`` — never add new top-level fields.
  - Never fabricate transport fields you do not have (ADR-0012 / contract §normalize).

Security (NB-1 — OWASP LLM01 indirect injection posture):
  If ``payload_snippet`` or any other field from this source reaches the LLM context,
  it MUST be delimited as untrusted data. See ARCHITECTURE.md §security-posture.
  Example wrapper: ``<untrusted_input source=\\"${name}\\">...</untrusted_input>``.
\"\"\"
from __future__ import annotations

from datetime import datetime, timezone

from firewatch_sdk import RawEvent, SecurityEvent

# Constant source_type — this plugin declares "${name}" as its type key and
# every SecurityEvent it emits carries this constant (PLUGIN_CONTRACT.md / Flag B).
SOURCE_TYPE: str = "${name}"

# TODO: Define your category map, severity map, OCSF class map, etc. here.
# See packages/sources/suricata/src/firewatch_suricata/normalize.py for a reference.


def normalize(raw: RawEvent, source_id: str) -> SecurityEvent:
    \"\"\"Map a ${title} raw event (wrapped in a RawEvent) to a SecurityEvent.

    ``source_type`` is always ``"${name}"`` (this plugin's constant).
    ``source_id`` is the caller-supplied instance name; this function never branches on it.
    (PLUGIN_CONTRACT.md "source_type vs source_id" / Flag B.)

    TODO: Replace the placeholder fields below with real mappings from ``raw.data``.
    \"\"\"
    d = raw.data

    # ── Timestamp ─────────────────────────────────────────────────────────────
    # TODO: Extract the real event timestamp from d.
    timestamp = raw.received_at

    # ── Action (ADR-0012) ─────────────────────────────────────────────────────
    # TODO: Map vendor action/disposition to "ALERT" or "BLOCK".
    # IDS detections → ALERT; IPS/WAF blocks → BLOCK.
    action = "ALERT"

    # ── Category ─────────────────────────────────────────────────────────────
    # TODO: Map vendor category/type to a FireWatch category string.
    category = "Unknown"

    # ── Severity ─────────────────────────────────────────────────────────────
    # TODO: Map vendor severity/priority to "critical"|"high"|"medium"|"low".
    severity = "medium"

    # ── Rule ─────────────────────────────────────────────────────────────────
    # TODO: Extract rule_id and rule_name from the raw event.
    rule_id: str | None = None
    rule_name: str | None = None

    # ── MITRE ATT&CK (ADR-0014) ──────────────────────────────────────────────
    # TODO: Derive attack_technique (e.g. "T1190") and attack_tactic (e.g. "TA0001")
    # from source metadata where available. Leave None if not derivable.
    attack_technique: str | None = None
    attack_tactic: str | None = None

    # ── Payload snippet (NB-1 reminder) ──────────────────────────────────────
    # TODO: Set payload_snippet from the relevant raw field, capped to 500 chars.
    # SECURITY (NB-1): If this snippet reaches the LLM, it MUST be delimited as
    # untrusted data to prevent indirect prompt injection (OWASP LLM01).
    payload_snippet: str | None = None

    return SecurityEvent(
        source_type=SOURCE_TYPE,   # constant — never branches on source_id (Flag B)
        source_id=source_id,       # caller's instance name, passed through as-is
        timestamp=timestamp,
        source_ip=str(d.get("src_ip") or ""),   # TODO: use the real field name
        action=action,              # type: ignore[arg-type]
        category=category,
        severity=severity,          # type: ignore[arg-type]
        rule_id=rule_id,
        rule_name=rule_name,
        payload_snippet=payload_snippet,
        attack_technique=attack_technique,
        attack_tactic=attack_tactic,
        raw_log=d,
    )
""")

_COLLECTOR_TMPL = Template("""\
\"\"\"${class_name} PullSource collector stub.

TODO: Implement the real collection loop here.

Must be cancellable and must not raise out of its loop (PLUGIN_CONTRACT.md hard rules).
\"\"\"
from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import datetime, timezone

from firewatch_sdk import RawEvent

from firewatch_${name}.config import ${class_name}Config

# Maximum events to yield per collect() call — prevents unbounded memory growth.
# TODO: Tune this cap for your source's typical event volume.
MAX_EVENTS_PER_COLLECT: int = 10_000


async def collect(
    cfg: ${class_name}Config, since: str | None
) -> AsyncIterator[RawEvent]:
    \"\"\"Yield RawEvents from the ${title} source newer than ``since``.

    ``since`` is an ISO-8601 watermark string or None for the initial full sync.

    TODO: Replace this stub with the real collection logic.
    \"\"\"
    # TODO: connect to your source, iterate events, filter by `since`,
    # and yield:
    #   RawEvent(
    #       source_type="${name}",
    #       received_at=datetime.now(timezone.utc),
    #       data=<raw dict>,
    #   )
    return
    yield  # pragma: no cover  (makes this an async generator)
""")

_LISTENER_TMPL = Template("""\
\"\"\"${class_name} PushSource listener stub.

TODO: Implement the real listener loop here.

Must be cancellable and must not raise out of its loop (PLUGIN_CONTRACT.md hard rules).
\"\"\"
from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable
from datetime import datetime, timezone

from firewatch_sdk import RawEvent

from firewatch_${name}.config import ${class_name}Config


async def run_listener(
    cfg: ${class_name}Config,
    emit: Callable[[list[RawEvent]], Awaitable[None]],
    stop_event: asyncio.Event,
) -> None:
    \"\"\"Listen for incoming events and call emit() with batches of RawEvents.

    Runs until ``stop_event`` is set.

    TODO: Replace this stub with the real listener (UDP/TCP/webhook/…).
    \"\"\"
    # TODO: bind your socket/endpoint, receive messages, coalesce into batches,
    # and call:
    #   await emit([
    #       RawEvent(
    #           source_type="${name}",
    #           received_at=datetime.now(timezone.utc),
    #           data={"line": <raw string/dict>, ...},
    #       )
    #   ])
    await stop_event.wait()
""")

_TEST_PLUGIN_TMPL = Template("""\
\"\"\"Tests for firewatch_${name} — entry-point isolation and SourcePlugin conformance.

EARS-1  Entry-point registration and zero-core-edit discovery.
EARS-2  config_schema: SecretStr fields, env > file > default.
EARS-3  No forbidden imports (no firewatch_core, no legacy).

TODO: Add normalize() and collection tests specific to your source.
See packages/sources/suricata/tests/test_plugin.py for a full reference.
\"\"\"
from __future__ import annotations

import sys
from pathlib import Path

from firewatch_sdk import PluginContext
from firewatch_sdk.testing import InMemoryScopedKV


def _ctx(source_id: str = "test-instance") -> PluginContext:
    \"\"\"Build a throwaway PluginContext for testing (ADR-0027 / InMemoryScopedKV).\"\"\"
    return PluginContext(kv=InMemoryScopedKV(), source_id=source_id)


# ---------------------------------------------------------------------------
# EARS-1: Entry-point discovery (modularity proof)
# ---------------------------------------------------------------------------


class TestEntryPointDiscovery:
    \"\"\"EARS-1 — the package registers ${class_name}Source under firewatch.sources and is
    discoverable with ZERO edits to firewatch-core.\"\"\"

    def test_entry_point_is_registered(self) -> None:
        \"\"\"After install, entry point group lists '${name}'.\"\"\"
        from importlib.metadata import entry_points

        eps = entry_points(group="firewatch.sources")
        names = {ep.name for ep in eps}
        assert "${name}" in names, (
            f"'${name}' not found in firewatch.sources entry points. Found: {names}"
        )

    def test_entry_point_loads_to_source_class(self) -> None:
        \"\"\"Loading the entry point yields a class whose instance satisfies SourcePlugin.\"\"\"
        from importlib.metadata import entry_points

        from firewatch_sdk import SourcePlugin

        eps = {ep.name: ep for ep in entry_points(group="firewatch.sources")}
        ep = eps["${name}"]
        cls = ep.load()
        plugin = cls()
        assert isinstance(plugin, SourcePlugin)

    def test_metadata_type_key(self) -> None:
        \"\"\"metadata().type_key must be exactly '${name}'.\"\"\"
        from firewatch_${name}.plugin import ${class_name}Source

        plugin = ${class_name}Source()
        assert plugin.metadata().type_key == "${name}"
        assert plugin.metadata().flavor in ("pull", "push")


# ---------------------------------------------------------------------------
# EARS-2: config_schema — SecretStr and env > file > default
# ---------------------------------------------------------------------------


class TestConfigSchema:
    \"\"\"EARS-2 — config_schema returns a Pydantic model with SecretStr secrets.\"\"\"

    def setup_method(self) -> None:
        from firewatch_${name}.plugin import ${class_name}Source
        self.plugin = ${class_name}Source()
        self.schema_cls = self.plugin.config_schema()

    def test_returns_pydantic_model_class(self) -> None:
        from pydantic import BaseModel
        assert issubclass(self.schema_cls, BaseModel)

    def test_secret_fields_use_secret_str(self) -> None:
        \"\"\"Any secret/key/token field must be SecretStr, never plain str.\"\"\"
        import typing
        from pydantic import SecretStr

        for field_name, field_info in self.schema_cls.model_fields.items():
            ann = field_info.annotation
            args = typing.get_args(ann)
            types_in_ann = {ann} | set(args)
            # If the field name suggests it's a secret, verify SecretStr is used
            if any(kw in field_name.lower() for kw in ("key", "secret", "token", "password", "pass")):
                assert SecretStr in types_in_ann, (
                    f"Field '{field_name}' looks like a secret but is not SecretStr. "
                    "PLUGIN_CONTRACT.md: secrets MUST use SecretStr."
                )


# ---------------------------------------------------------------------------
# EARS-3: no forbidden imports
# ---------------------------------------------------------------------------


class TestNoForbiddenImports:
    \"\"\"EARS-3 — firewatch_${name} must depend only on firewatch_sdk; never core or legacy.\"\"\"

    def test_does_not_import_firewatch_core(self) -> None:
        \"\"\"No source file may import firewatch_core.\"\"\"
        src_dir = Path(__file__).parent.parent / "src" / "firewatch_${name}"
        for py_file in src_dir.glob("*.py"):
            content = py_file.read_text()
            assert "firewatch_core" not in content, (
                f"{py_file.name} imports firewatch_core — forbidden (PLUGIN_CONTRACT.md)"
            )

    def test_does_not_import_legacy(self) -> None:
        \"\"\"No source file may import legacy/.\"\"\"
        import re
        import_re = re.compile(r"^\\s*(from legacy|import legacy)\\b", re.MULTILINE)
        src_dir = Path(__file__).parent.parent / "src" / "firewatch_${name}"
        for py_file in src_dir.glob("*.py"):
            content = py_file.read_text()
            match = import_re.search(content)
            assert match is None, (
                f"{py_file.name} imports legacy — forbidden: {match.group()!r}"
            )

    def test_only_firewatch_sdk_from_firewatch_namespace(self) -> None:
        \"\"\"Imports from firewatch_* namespace must be firewatch_sdk or own module only.\"\"\"
        src_dir = Path(__file__).parent.parent / "src" / "firewatch_${name}"
        for py_file in src_dir.glob("*.py"):
            content = py_file.read_text()
            for line in content.splitlines():
                stripped = line.strip()
                if stripped.startswith("from firewatch_") or stripped.startswith("import firewatch_"):
                    assert "firewatch_sdk" in stripped or "firewatch_${name}" in stripped, (
                        f"{py_file.name}: forbidden import: {stripped!r}"
                    )
""")

_TEST_NORMALIZE_TMPL = Template("""\
\"\"\"Golden-test stub for firewatch_${name}.normalize — fill in with real fixtures.

This file is a template: replace the TODO sections with actual vendor log samples
and expected SecurityEvent field values (PLUGIN_CONTRACT.md golden-test requirement).

Fixture IP addresses MUST use RFC 5737 documentation ranges:
  192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24
(testing-conventions skill / CI gitleaks gate).

NEVER record fixtures from legacy/ output — build them to the published standard
(ADR-0024: OCSF/ADR-0020, MITRE/ADR-0014, action/ADR-0012).
\"\"\"
from __future__ import annotations

from datetime import datetime, timezone

import pytest

from firewatch_sdk import RawEvent


def _raw(data: dict) -> RawEvent:  # type: ignore[type-arg]
    \"\"\"Helper: wrap a raw dict in a RawEvent for testing.\"\"\"
    return RawEvent(
        source_type="${name}",
        received_at=datetime(2026, 1, 15, 10, 0, 0, tzinfo=timezone.utc),
        data=data,
    )


class TestNormalizeGolden:
    \"\"\"Golden tests: vendor log sample → expected SecurityEvent fields.

    TODO: Add one test method per fixture case. For each:
      1. Build the raw vendor event dict (use RFC 5737 IPs: 192.0.2.x etc.)
      2. Call plugin.normalize(raw, source_id="test-instance")
      3. Assert each expected SecurityEvent field value.

    See packages/sources/suricata/tests/test_plugin.py::TestNormalizeBasic for style.
    \"\"\"

    def setup_method(self) -> None:
        from firewatch_${name}.plugin import ${class_name}Source
        self.plugin = ${class_name}Source()

    def test_source_type_is_constant(self) -> None:
        \"\"\"source_type must always be '${name}' regardless of source_id (Flag B).\"\"\"
        # TODO: Replace {} with a minimal real vendor event dict.
        raw = _raw({})
        event = self.plugin.normalize(raw, source_id="test-instance")
        assert event.source_type == "${name}"

    def test_source_id_passed_through(self) -> None:
        \"\"\"source_id is the user's instance name; passed through, not invented.\"\"\"
        raw = _raw({})
        event = self.plugin.normalize(raw, source_id="my-sensor")
        assert event.source_id == "my-sensor"

    # TODO: Add tests for action, severity, category, rule_id, rule_name,
    # payload_snippet, attack_technique, attack_tactic, etc.
    # Use RFC 5737 IPs: 192.0.2.x / 198.51.100.x / 203.0.113.x
    #
    # Example:
    #
    # def test_action_alert_for_detection(self) -> None:
    #     raw = _raw({"vendor_action": "detected", "src_ip": "203.0.113.5"})
    #     event = self.plugin.normalize(raw, source_id="test-instance")
    #     assert event.action == "ALERT"
    #
    # def test_action_block_for_block(self) -> None:
    #     raw = _raw({"vendor_action": "blocked", "src_ip": "203.0.113.5"})
    #     event = self.plugin.normalize(raw, source_id="test-instance")
    #     assert event.action == "BLOCK"
""")


# ---------------------------------------------------------------------------
# Scaffold engine
# ---------------------------------------------------------------------------


def _render(tmpl: Template, **kwargs: str) -> str:
    """Render a Template with the given keyword arguments."""
    return tmpl.substitute(**kwargs)


def scaffold(
    name: str,
    *,
    flavor: str,
    output_dir: Path,
) -> Path:
    """Generate a new source plugin package skeleton.

    Parameters
    ----------
    name:
        The source type key (must match ``^[a-z][a-z0-9_]*$``;
        must start with a lowercase letter).
    flavor:
        Either ``"pull"`` or ``"push"``.
    output_dir:
        Root directory under which ``packages/sources/<name>/`` is created.

    Returns
    -------
    Path
        The path of the generated package root (``<output_dir>/packages/sources/<name>/``).

    Raises
    ------
    ValueError
        If *name* is invalid or *flavor* is not ``"pull"``/``"push"``.
    FileExistsError
        If the target directory already exists (no silent overwrite).
    """
    validate_name(name)

    if flavor not in ("pull", "push"):
        raise ValueError(
            f"flavor must be 'pull' or 'push', got {flavor!r}."
        )

    pkg_root = output_dir / "packages" / "sources" / name
    if pkg_root.exists():
        raise FileExistsError(
            f"Package directory already exists: {pkg_root}\n"
            f"Refusing to overwrite '{name}'. "
            "Remove the directory manually if you want to regenerate."
        )

    class_name = _camel(name)
    title = name.replace("_", " ").title()
    env_prefix = _env_prefix(name)

    ctx: dict[str, str] = {
        "name": name,
        "class_name": class_name,
        "title": title,
        "env_prefix": env_prefix,
    }

    src_dir = pkg_root / "src" / f"firewatch_{name}"
    tests_dir = pkg_root / "tests"

    src_dir.mkdir(parents=True)
    tests_dir.mkdir(parents=True)

    # ── pyproject.toml ────────────────────────────────────────────────────────
    (pkg_root / "pyproject.toml").write_text(_render(_PYPROJECT_TMPL, **ctx), encoding="utf-8")

    # ── src/firewatch_<name>/__init__.py ──────────────────────────────────────
    (src_dir / "__init__.py").write_text("", encoding="utf-8")

    # ── src/firewatch_<name>/plugin.py ────────────────────────────────────────
    plugin_tmpl = _PLUGIN_PULL_TMPL if flavor == "pull" else _PLUGIN_PUSH_TMPL
    (src_dir / "plugin.py").write_text(_render(plugin_tmpl, **ctx), encoding="utf-8")

    # ── src/firewatch_<name>/config.py ────────────────────────────────────────
    (src_dir / "config.py").write_text(_render(_CONFIG_TMPL, **ctx), encoding="utf-8")

    # ── src/firewatch_<name>/normalize.py ─────────────────────────────────────
    (src_dir / "normalize.py").write_text(_render(_NORMALIZE_TMPL, **ctx), encoding="utf-8")

    # ── src/firewatch_<name>/collector.py or listener.py ─────────────────────
    if flavor == "pull":
        (src_dir / "collector.py").write_text(_render(_COLLECTOR_TMPL, **ctx), encoding="utf-8")
    else:
        (src_dir / "listener.py").write_text(_render(_LISTENER_TMPL, **ctx), encoding="utf-8")

    # ── tests/__init__.py ─────────────────────────────────────────────────────
    (tests_dir / "__init__.py").write_text("", encoding="utf-8")

    # ── tests/test_plugin.py ─────────────────────────────────────────────────
    (tests_dir / "test_plugin.py").write_text(_render(_TEST_PLUGIN_TMPL, **ctx), encoding="utf-8")

    # ── tests/test_normalize.py ──────────────────────────────────────────────
    (tests_dir / "test_normalize.py").write_text(_render(_TEST_NORMALIZE_TMPL, **ctx), encoding="utf-8")

    return pkg_root
