"""Case File routes (ADR-0053 D4 / issue #534 + #535).

Routes
------
POST /cases
    Create a new case file. Returns 201 + {"id": <int>}.

GET /cases
    Cursor-paginated list of cases (ADR-0029 envelope).

GET /cases/{case_id}
    Full case_file record.  Returns 404 when not found.

PATCH /cases/{case_id}/disposition
    Set the case disposition (true-positive / false-positive / benign / open).
    Returns 200 on success; 404 when case not found; 422 on invalid value.

POST /cases/{case_id}/notes
    Add a markdown note to a case.  Returns 201 + {"id": <int>}.
    author defaults to 'local operator' (ADR-0053 D3 auth-aware seam).

GET /cases/{case_id}/notes
    Return all notes for a case in chronological order.

GET /cases/{case_id}/timeline
    Assemble event + analysis references at read time (ADR-0041 / ADR-0053 D2).
    Returns 404 when case not found.

POST /cases/{case_id}/events
    Link a security_event or ai_analysis reference to a case (EARS-2).
    Returns 201 + {"id": <int>}.

POST /cases/{case_id}/summary  (issue #535 B1-polish, ADR-0053 D2)
    Generate a local-LLM draft summary for the case, reusing the ML-7
    narration path (ADR-0043 / EARS-1).  Persists the draft as a case_note
    with ai_drafted=1 (ADR-0035 / EARS-2).  Degrades to rule-only summary
    when the LLM is unavailable (EARS-5).  Suggest-only — no auto-disposition
    (EARS-6 / ADR-0015).
    Returns 201 + {"note_id", "narrative", "provenance", "collected_fields", "ai_status"}.

Route class: B (writes) / C (reads) — ADR-0026 gating applies when the API
is exposed beyond loopback (deferred to MP.3 / ADR-0026 Decisions 2-3 / issue #548).

Security
--------
- body_md is operator text that may embed attacker-controlled content (OWASP LLM01);
  it must be rendered as sanitized markdown in the UI — never raw HTML (ADR-0029 D3).
- All parameterised queries in the adapter; no interpolation.
- 404 errors do NOT echo attacker-controlled record content (OWASP API4:2023).
- limit clamped to 200 (prevents large inadvertent reads).
"""
from __future__ import annotations

import logging
from typing import Any, Literal

from fastapi import APIRouter, HTTPException, Query, Request
from pydantic import BaseModel, Field

logger = logging.getLogger("firewatch.api.cases")

router = APIRouter(tags=["cases"])

_DEFAULT_LIMIT = 50
_MAX_LIMIT = 200

# Valid disposition values (mirrors caps.py; kept here for Pydantic Literal check).
_DispositionLiteral = Literal["true-positive", "false-positive", "benign", "open"]


# ---------------------------------------------------------------------------
# Request bodies
# ---------------------------------------------------------------------------


class _CreateCaseBody(BaseModel):
    """Request body for POST /cases."""

    title: str = Field(..., min_length=1, max_length=500, description="Case title")
    subject: str = Field(
        ..., min_length=1, max_length=500,
        description="Entity under investigation (e.g. source IP, hostname)",
    )
    disposition: _DispositionLiteral = Field(
        default="open", description="Initial disposition"
    )


class _AddNoteBody(BaseModel):
    """Request body for POST /cases/{case_id}/notes.

    author defaults to 'local operator' (ADR-0053 D3 auth-aware seam).
    Post-ADR-0026, the API layer can override author from the authenticated principal.
    """

    body_md: str = Field(
        ..., min_length=1,
        description="Markdown note body (max 32 KiB). Rendered as sanitized markdown in the UI.",
    )
    author: str = Field(
        default="local operator",
        min_length=1,
        max_length=500,
        description="Note author identity. Defaults to 'local operator'.",
    )
    ai_drafted: bool = Field(
        default=False, description="True when the body was generated by the local LLM (ADR-0035)."
    )


class _SetDispositionBody(BaseModel):
    """Request body for PATCH /cases/{case_id}/disposition."""

    disposition: _DispositionLiteral = Field(..., description="New disposition value")


class _LinkEventBody(BaseModel):
    """Request body for POST /cases/{case_id}/events."""

    ref_kind: str = Field(
        ..., min_length=1, max_length=100,
        description="Kind of reference: 'security_event' or 'ai_analysis'.",
    )
    ref_id: str = Field(
        ..., min_length=1, max_length=200,
        description="Stringified ID in the referenced table.",
    )


# ---------------------------------------------------------------------------
# Dependency helper
# ---------------------------------------------------------------------------


def _get_case_store(request: Request) -> Any | None:
    """Resolve the SqliteCaseStore from app state.

    Returns None when the store is not yet wired (degrades to 503).
    """
    return getattr(request.app.state, "case_store", None)


def _require_case_store(request: Request) -> Any:
    store = _get_case_store(request)
    if store is None:
        raise HTTPException(
            status_code=503,
            detail="Case store not available — service starting up.",
        )
    return store


# ---------------------------------------------------------------------------
# POST /cases
# ---------------------------------------------------------------------------


@router.post("/cases", status_code=201, response_model=None,
             summary="Create a new case file")
async def create_case(request: Request, body: _CreateCaseBody) -> dict[str, Any]:
    """Create a new case file (EARS-1).

    Returns ``{"id": <int>}`` on success (201).
    Returns 503 when the case store is not wired.
    """
    store = _require_case_store(request)
    try:
        case_id = await store.create_case(
            title=body.title,
            subject=body.subject,
            disposition=body.disposition,
        )
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.error("POST /cases: create_case failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=503, detail="Case store write failed.") from exc
    return {"id": case_id}


# ---------------------------------------------------------------------------
# GET /cases
# ---------------------------------------------------------------------------


@router.get("/cases", response_model=None, summary="Paginated list of cases")
async def list_cases(
    request: Request,
    limit: int = Query(default=_DEFAULT_LIMIT, ge=1, le=_MAX_LIMIT),
    cursor: str | None = Query(default=None),
    subject: str | None = Query(default=None, description=(
        "Optional equality filter on the case subject field (e.g. source IP). "
        "When provided, only cases whose subject exactly matches this value are "
        "returned, newest first. When omitted, all cases are returned (issue #757)."
    )),
) -> dict[str, Any]:
    """Return a cursor-paginated list of case files (ADR-0029 envelope).

    Newest cases first. Response: ``{"items": [...], "next_cursor": str|null, "has_more": bool}``.

    When ``subject`` is provided, the result is filtered to cases whose
    ``subject`` field exactly equals that value (parameterized SQL — no
    injection risk).  The frontend uses this for find-or-create dedup (issue #757).
    """
    store = _require_case_store(request)
    try:
        page = await store.list_cases(limit=limit, cursor=cursor, subject=subject)
    except Exception as exc:
        logger.error("GET /cases: list_cases failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    return page


# ---------------------------------------------------------------------------
# GET /cases/{case_id}
# ---------------------------------------------------------------------------


@router.get("/cases/{case_id}", response_model=None, summary="Get a case file by ID")
async def get_case(request: Request, case_id: int) -> dict[str, Any]:
    """Return the full case_file record for *case_id*.

    Returns 404 when the case does not exist.
    Returns 503 when the store is not wired.
    """
    store = _require_case_store(request)
    try:
        case = await store.get_case(case_id)
    except Exception as exc:
        logger.error("GET /cases/%d: get_case failed: %s", case_id, exc, exc_info=True)
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    if case is None:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")
    return case


# ---------------------------------------------------------------------------
# PATCH /cases/{case_id}/disposition
# ---------------------------------------------------------------------------


@router.patch(
    "/cases/{case_id}/disposition",
    response_model=None,
    summary="Set the case disposition",
)
async def set_disposition(
    request: Request, case_id: int, body: _SetDispositionBody
) -> dict[str, Any]:
    """Update the disposition of a case (EARS-5).

    Valid values: ``true-positive``, ``false-positive``, ``benign``, ``open``.
    Returns ``{"ok": true}`` on success.
    Returns 404 when the case does not exist; 422 on invalid disposition.
    """
    store = _require_case_store(request)
    try:
        await store.set_disposition(case_id=case_id, disposition=body.disposition)
    except LookupError:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.error(
            "PATCH /cases/%d/disposition: set_disposition failed: %s",
            case_id, exc, exc_info=True,
        )
        raise HTTPException(status_code=503, detail="Case store write failed.") from exc
    return {"ok": True}


# ---------------------------------------------------------------------------
# POST /cases/{case_id}/notes
# ---------------------------------------------------------------------------


@router.post(
    "/cases/{case_id}/notes",
    status_code=201,
    response_model=None,
    summary="Add a markdown note to a case",
)
async def add_note(
    request: Request, case_id: int, body: _AddNoteBody
) -> dict[str, Any]:
    """Append a markdown note to a case (EARS-3 / EARS-4).

    ``author`` defaults to ``'local operator'`` (ADR-0053 D3 auth-aware seam).
    Returns ``{"id": <int>}`` on success (201).
    Returns 404 when the case does not exist; 422 when body exceeds cap.

    Security: ``body_md`` may embed attacker-controlled content; it MUST be
    rendered as sanitized markdown in the UI — never raw HTML (ADR-0029 D3).
    """
    store = _require_case_store(request)
    try:
        note_id = await store.add_note(
            case_id=case_id,
            body_md=body.body_md,
            author=body.author,
            ai_drafted=body.ai_drafted,
        )
    except LookupError:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.error(
            "POST /cases/%d/notes: add_note failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store write failed.") from exc
    return {"id": note_id}


# ---------------------------------------------------------------------------
# GET /cases/{case_id}/notes
# ---------------------------------------------------------------------------


@router.get(
    "/cases/{case_id}/notes",
    response_model=None,
    summary="List notes for a case (chronological)",
)
async def list_notes(request: Request, case_id: int) -> dict[str, Any]:
    """Return all notes for *case_id* in chronological order.

    Security: ``body_md`` must be rendered as sanitized markdown (ADR-0029 D3).
    """
    store = _require_case_store(request)
    try:
        notes = await store.list_notes(case_id)
    except Exception as exc:
        logger.error(
            "GET /cases/%d/notes: list_notes failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    return {"case_id": case_id, "notes": notes}


# ---------------------------------------------------------------------------
# POST /cases/{case_id}/events   (link a reference)
# ---------------------------------------------------------------------------


@router.post(
    "/cases/{case_id}/events",
    status_code=201,
    response_model=None,
    summary="Link a security_event or ai_analysis reference to a case",
)
async def link_event(
    request: Request, case_id: int, body: _LinkEventBody
) -> dict[str, Any]:
    """Link an event / analysis reference to a case (EARS-2 / ADR-0041).

    Stores a reference only — no denormalized copy (ADR-0041 discipline).
    Returns ``{"id": <int>}`` on success (201).
    Returns 404 when the case does not exist.
    """
    store = _require_case_store(request)
    try:
        ev_id = await store.link_event(
            case_id=case_id, ref_kind=body.ref_kind, ref_id=body.ref_id
        )
    except LookupError:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.error(
            "POST /cases/%d/events: link_event failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store write failed.") from exc
    return {"id": ev_id}


# ---------------------------------------------------------------------------
# GET /cases/{case_id}/timeline
# ---------------------------------------------------------------------------


@router.get(
    "/cases/{case_id}/timeline",
    response_model=None,
    summary="Timeline of event/analysis references for a case (assembled at read time)",
)
async def get_timeline(request: Request, case_id: int) -> dict[str, Any]:
    """Return the timeline for *case_id* (EARS-2 / ADR-0041 / ADR-0053 D2).

    References are assembled at read time from case_events — no denormalized
    copies are stored.  Returns 404 when the case does not exist.
    """
    store = _require_case_store(request)

    # Check case exists first so we can return 404 rather than empty events.
    try:
        case = await store.get_case(case_id)
    except Exception as exc:
        logger.error(
            "GET /cases/%d/timeline: get_case check failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    if case is None:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")

    try:
        timeline = await store.get_timeline(case_id)
    except Exception as exc:
        logger.error(
            "GET /cases/%d/timeline: get_timeline failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    return timeline


# ---------------------------------------------------------------------------
# POST /cases/{case_id}/summary  (issue #535 B1-polish, ADR-0053 D2)
# ---------------------------------------------------------------------------


@router.post(
    "/cases/{case_id}/summary",
    status_code=201,
    response_model=None,
    summary="Generate a local-LLM draft summary for a case (B1-polish, ADR-0053 D2)",
)
async def draft_case_summary(request: Request, case_id: int) -> dict[str, Any]:
    """Generate a local-LLM draft summary for a case (issue #535 / ADR-0053 D2).

    **EARS-1:** Reuses the ML-7 narration path (ADR-0043) — local LLM only,
    zero egress (ADR-0022/0047).  Builds the narration prompt from
    ``build_narration_prompt`` / ``build_rule_only_narration``.

    **EARS-2:** The draft is persisted as a ``case_notes`` row with
    ``ai_drafted=1`` (ADR-0035 provenance tag).

    **EARS-3:** Each claim in the draft is grounded in the verdict-ledger /
    evidence-chain fields surfaced by ``pipeline.analyze_ip_detailed``.
    Anti-fabrication: only non-null fields are injected into the prompt.

    **EARS-5:** When the LLM is unavailable, degrades to a deterministic
    rule-only summary (``provenance='rule'``) — same degrade contract as
    ``GET /threats/{ip}/narration``.

    **EARS-6:** Suggest-only — does NOT auto-close or auto-set disposition.
    (ADR-0015 suggest tier.)

    The case's ``subject`` field is treated as the entity identifier (source IP)
    used to fetch the detailed analysis via the pipeline.

    Returns
    -------
    ``{"note_id": int, "narrative": str, "provenance": str,
       "collected_fields": list[str], "ai_status": str}``

    Raises
    ------
    404 — case not found.
    503 — case store or pipeline not available.
    """
    store = _require_case_store(request)
    pipeline = getattr(request.app.state, "pipeline", None)

    # Resolve the case so we know its subject (entity under investigation).
    try:
        case = await store.get_case(case_id)
    except Exception as exc:
        logger.error(
            "POST /cases/%d/summary: get_case failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store read failed.") from exc
    if case is None:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")

    subject: str = str(case.get("subject", "") or "")

    # ---------------------------------------------------------------------------
    # Build the narration prompt from the case subject (EARS-1 / EARS-3).
    # We reuse build_narration_prompt / build_rule_only_narration from ML-7
    # (ADR-0043).  When the pipeline is available and the LLM engine ran, we
    # call build_narration_prompt and invoke analyze_concise exactly as the
    # threats narration route does.  Otherwise we degrade to rule-only (EARS-5).
    # ---------------------------------------------------------------------------

    # Local imports keep the module surface clean (mirrors threats.py precedent).
    from firewatch_core.ai.narration import (  # local import — no circular risk
        build_narration_prompt,
        build_rule_only_narration,
    )

    # Attempt to fetch detailed analysis when the pipeline is available.
    # When the subject is not a known IP (e.g. a hostname), analyze_ip_detailed
    # returns {"error": ...} which we catch and fall back to rule-only.
    detail: dict[str, Any] = {}
    llm_available = False

    if pipeline is not None and subject:
        try:
            detail = await pipeline.analyze_ip_detailed(subject, include_ai=True)
            if "error" in detail:
                # Subject not in the event store — rule-only degrade is honest.
                detail = {}
            else:
                ai_status_val = str(detail.get("ai_status", "unavailable"))
                llm_available = ai_status_val not in ("unavailable", "skipped", "disabled")
        except Exception:
            logger.warning(
                "POST /cases/%d/summary: analyze_ip_detailed failed for subject=%r — "
                "degrading to rule-only (EARS-5 / ADR-0015)",
                case_id, subject,
            )
            detail = {}

    ai_status: str = str(detail.get("ai_status", "unavailable"))
    score_derivation: str = str(detail.get("score_derivation", "rule"))

    narrative_text = ""
    provenance = "rule"
    collected_fields: list[str] = []

    if llm_available and detail and pipeline is not None:
        # LLM path — mirrors threats.py get_ip_narration exactly (EARS-1).
        narration_prompt = build_narration_prompt(subject or "unknown", detail)
        try:
            samples = [{"rule_id": "case-summary", "category": "case-summary",
                        "count": 1, "payload": ""}]
            raw = await pipeline.ai_engine.analyze_concise(
                ip=subject or "unknown",
                total_events=int(detail.get("total_events", 0)),
                blocked_events=int(detail.get("blocked_events", 0)),
                rules_triggered=1,
                first_seen=str(detail.get("first_seen") or ""),
                last_seen=str(detail.get("last_seen") or ""),
                samples=samples,
                security_mode=False,
                _narration_prompt=narration_prompt,
            )
            narrative_text = (
                raw.get("narrative")
                or raw.get("intent")
                or raw.get("executive_summary")
                or ""
            )
            # Strip PROVENANCE line if present (mirrors threats.py).
            if "PROVENANCE:" in narrative_text:
                parts = narrative_text.split("PROVENANCE:", 1)
                narrative_text = parts[0].strip()
                prov_line = parts[1].strip() if len(parts) > 1 else ""
                collected_fields = [f.strip() for f in prov_line.split(",") if f.strip()]
            provenance = "ai" if score_derivation == "rule" else score_derivation
        except Exception:
            logger.warning(
                "POST /cases/%d/summary: LLM narration failed for subject=%r — "
                "degrading to rule-only (EARS-5 / ADR-0015)",
                case_id, subject,
            )
            # Fall through to rule-only below.
            narrative_text = ""
            provenance = "rule"
            collected_fields = []

    if not narrative_text:
        # Rule-only degrade path (EARS-5): deterministic, no LLM call.
        if detail:
            rule_result = build_rule_only_narration(subject or "unknown", detail)
        else:
            # Minimal rule-only summary when even the pipeline is unavailable.
            rule_result = {
                "narrative": (
                    f"Case #{case_id} — subject: {subject or 'unknown'}. "
                    "Detailed analysis unavailable; review the timeline and notes manually."
                ),
                "provenance": "rule",
                "collected_fields": ["case_id", "subject"],
                "ai_status": "unavailable",
            }
        narrative_text = rule_result["narrative"]
        provenance = rule_result["provenance"]
        collected_fields = rule_result.get("collected_fields", [])
        ai_status = rule_result.get("ai_status", "unavailable")

    # ---------------------------------------------------------------------------
    # Persist the draft as a case_note with ai_drafted=True (EARS-2 / ADR-0035).
    # This is suggest-only: no auto-disposition, no auto-close (EARS-6 / ADR-0015).
    # ---------------------------------------------------------------------------
    try:
        note_id = await store.add_note(
            case_id=case_id,
            body_md=narrative_text,
            author="local operator",
            ai_drafted=True,
        )
    except LookupError:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found.")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.error(
            "POST /cases/%d/summary: add_note failed: %s", case_id, exc, exc_info=True
        )
        raise HTTPException(status_code=503, detail="Case store write failed.") from exc

    return {
        "note_id": note_id,
        "narrative": narrative_text,
        "provenance": provenance,
        "collected_fields": collected_fields,
        "ai_status": ai_status,
    }
